trigger:
  branches:
    include:
      - dev

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/ImageRed.sln'

  
steps:
- task: NuGetToolInstaller@1
  name: 'NugetToolInstaller'

- task: NuGetCommand@2
  name: 'RestoreNuget'
  inputs:
    restoreSolution: '$(solution)'


- task: DotNetCoreCLI@2
  name: 'buildArtifact'
  inputs:
    command: 'build'
    publishWebProjects: false
    projects: '$(solution)'
    arguments: '-configuration $(buildConfiguration) -- output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  name: 'publishArtifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'ImageRed-artifact'
    publishLocation: 'Container'